name: Check Issue every month
run-name: Monthly issue check
on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
jobs:
  creating-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: list issue
        run: gh issue list -l "question" -s "open" -json
