name: Check Issue every month
run-name: Monthly issue check
on:
  schedule:
    - cron: '*/5 * * * *'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
jobs:
  confirming-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: list issue
        run: gh issue list -l "question" -s "open" | grep OPEN && if [ $? -eq 0 ]; then echo notify; fi || echo end
