name: Check Issue every month
run-name: Monthly issue check
on:
#  schedule:
#    - cron: '15 1 * * *'
  pull_request:
    paths:
      - .github/workflows

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
  DISCORD_USERNAME: ${{ vars.DISCORD_USERNAME }}
  DISCORD_ICON: ${{ vars.DISCORD_ICON_URL }}
  ISSUE_LABEL: ${{ vars.ISSUE_LABEL_FOR_GIHUB_ISSUE }}
jobs:
  confirming-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: list issue
        id: confirm_issue_list
        continue-on-error: true
        run: gh issue list -l "$ISSUE_LABEL" -s "open" | grep OPEN && if [ $? -eq 0 ]; then exit 1; fi || exit 0
      - name: notification
        if: ${{ steps.confirm_issue_list.outcome == 'failure' }}
        run: chmod 755 ./scripts/notifyToDiscord.sh && ./scripts/notifyToDiscord.sh
