name: Creating Issue every month
run-name: Monthly issue creation
on:
  schedule:
    - cron: '*/3 * * * *'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
jobs:
  creating-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: view
        run: gh issue create -t 【`date "+%y%m"`】今月のアクション -l "automated,actions"
