name: How work GitHub CLI
run-name: GitHub CLI try
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: view
        run: gh repo view Shunshun94/discord-bcdicebot
