name: pre-merge-build
run-name: pre merge build
on: pull_request
jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: execute test
        run: mvn test
