name: pre-merge-build
run-name: pre merge build
on:
  pull_request:
    paths:
      - src/*
jobs:
  execute-test:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mvn test
