name: release
run-name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_RELEASE_GITHUB_CLI }}
  TAG: ${{ github.ref }}
  JAR_FILE: 'target/GitHubActionLearn.jar'
  ZIP_FILE: 'GitHubActionLearn.zip'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: mvn clean compile package
      - name: rename jar
        run: mv target/GitHubActionLearn-*.jar $JAR_FILE
#     - name: archive
#       uses: actions/upload-artifact@v3
#       with:
#         name: archive jar
#         path: $JAR_FILE
#     - name: display tag
#       env:
#         TAG: ${{ github.ref }}
#       run: echo ${TAG##*/}
      - name: create zip file
        run: jar -cvfM $ZIP_FILE $JAR_FILE
      - name: append README.md to zip file
        run: jar -uvf $ZIP_FILE README.md
      - name: release zip
        run: gh release create ${TAG##*/} $ZIP_FILE $JAR_FILE
